---
title: Peter McDonagh
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@petermcdonagh.com
description: Peter Reaper-Reynolds is a freelance designer
baseurl: 
url: http://pete.studio
twitter_username: petermcdonagh_
github_username: peterjrr
markdown: kramdown
