---
title: Peter McDonagh
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hi@petermcdonagh.com
description: Peter McDonagh is a freelance designer
baseurl: 
url: http://petermcdonagh.com
twitter_username: petermcdonagh_
github_username: petemcd
markdown: kramdown
